# Generated by Django 2.1.3 on 2019-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_adsoyad', models.CharField(max_length=100, verbose_name='Gönderenin Ad-Soyadı')),
                ('iletisim_ulasim', models.CharField(max_length=100, verbose_name='Ulaşım Bilgileri')),
                ('iletisim_mesaj', models.TextField(verbose_name='Mesaj')),
                ('iletisim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İletişim Formu Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('-iletisim_tarihi',),
            },
        ),
    ]
